### ISSUE TITLE
wasm binding stuff (i wanna run it on a js front-end)

### ISSUE THREAD

**Issue by Joshix-1** [asozialesnetzwerk/hangman_solver#13]

**Comment by 0xWebMilk** [comment]
**You didn't specify what exactly the problem is, the question is not worded correctly. Please clarify or close the topic.**

**Comment by Joshix-1** [comment]
what don't you understand? What is not clear??

**Comment by Joshix-1** [comment]
Works: https://github.asozial.org/hangman_solver/
